version: '2.3'

services:

  portfolio-web:
    container_name: portfolio-web
    hostname: portfolio-web
    image: nginx:stable-alpine
    networks:
      portfolio-net:
        ipv4_address: 172.101.0.12
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - portfolio-contents
    depends_on:
      - portfolio-php
      - portfolio-composer
      - portfolio-node

  portfolio-php:
    container_name: portfolio-php
    hostname: portfolio-php
    image: php:7.2.12-fpm-alpine
    user: "1000:1000"
    networks:
      portfolio-net:
        ipv4_address: 172.101.0.13
    volumes_from:
      - portfolio-contents

  portfolio-composer:
    container_name: portfolio-composer
    hostname: portfolio-composer
    image: composer:1.7.3
    user: "1000:1000"
    volumes:
        - ${PWD}/web:/app
    depends_on:
      - portfolio-php

  portfolio-node:
    container_name: portfolio-node
    hostname: portfolio-node
    image: node:10.13-alpine
    user: "1000:1000"
    volumes_from:
      - portfolio-contents

  portfolio-contents:
    container_name: portfolio-contents
    hostname: portfolio-contents
    image: busybox
    volumes:
        - ${PWD}/web:/web

